#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/welwel11/izin/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit 0
  fi
}
checking_sc
clear
#Domain
domain=$(cat /etc/xray/domain)

echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "                SSH & OpenVPN           "
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${ORANGE}[1].${NC}\033[0;36m BUAT AKUN SSH${NC}"
echo -e "  ${ORANGE}[2].${NC}\033[0;36m BUAT TRIAL AKUN SSH${NC}"
echo -e "  ${ORANGE}[3].${NC}\033[0;36m PERBARUI AKUN SSH${NC}"
echo -e "  ${ORANGE}[4].${NC}\033[0;36m CEK LOGIN AKUN SSH${NC}"
echo -e "  ${ORANGE}[5].${NC}\033[0;36m DAFTAR AKUN SSH${NC}"
echo -e "  ${ORANGE}[6].${NC}\033[0;36m HAPUS AKUN SSH${NC}"
echo -e "  ${ORANGE}[7].${NC}\033[0;36m HAPUS AKUN EXPIRED${NC}"
echo -e "  ${ORANGE}[8].${NC}\033[0;36m SET AUTO KILL${NC}"
echo -e "  ${ORANGE}[9].${NC}\033[0;36m CEK MULTY LOGIN SSH${NC}"
echo -e "  ${ORANGE}[10].${NC}\033[0;36m KUNCI AKUN SSH${NC}"
echo -e "  ${ORANGE}[11].${NC}\033[0;36m BUKA KUNCI AKUN SSH${NC}"
echo -e "  ${ORANGE}[x].${NC}\033[0;36m  Exit ${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
read -p "Select From Options [ 1 - 11 or x ] : " menu
echo -e ""
case $menu in
1)
    addssh
    ;;
2)
    trial
    ;;
3)
    renewssh
    ;;
4)
    cekssh
    ;;
5)
    member
    ;;
6)
    delssh
    ;;
7)
    delexp
    ;;
8)
    autokill
    ;;
9)
    ceklim
    ;;
10) 
    clear
    lock
   ;;
11)
    clear
    unlock
    ;;
*)
    menu
    ;;
esac