#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/rendiap100/izin/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    exit 0
  fi
}
checking_sc
clear
clear
echo -e "╔═════════════════◈◈═════════════════╗" | lolcat
echo -e "              MENU TROJAN              $NC"
echo -e "╚═════════════════◈◈═════════════════╝" | lolcat
echo -e "╔═════════════════◈◈═════════════════╗" | lolcat
echo -e "  ${ORANGE}[01].${NC} \033[0;36m BUAT AKUN TROJAN${NC}"
echo -e "  ${ORANGE}[02].${NC} \033[0;36m BUAT TRIAL AKUN TROJAN${NC}"
echo -e "  ${ORANGE}[03].${NC} \033[0;36m HAPUS AKUN TROJAN${NC}"
echo -e "  ${ORANGE}[04].${NC} \033[0;36m PERBARUI AKUN TROJAN${NC}"
echo -e "  ${ORANGE}[05].${NC} \033[0;36m PERBARUI IP TROJAN${NC}"
echo -e "  ${ORANGE}[06].${NC} \033[0;36m PERBARUI KUOTA TROJAN${NC}"
echo -e "  ${ORANGE}[07].${NC} \033[0;36m CEK LOGIN AKUN TROJAN${NC}"
echo -e "  ${ORANGE}[08].${NC} \033[0;36m RECOVERY AKUN TROJAN${NC}"
echo -e "  ${ORANGE}[00].${NC} \033[0;36m ENTER UNTUK KEMBALI KE MENU ${NC}"
echo -e "╚═════════════════◈◈═════════════════╝" | lolcat
echo -e ""
read -p "MENU : " menu
case $menu in
1) clear ;
    addtr
    ;;
2) clear ;
    trialtr
    ;;
3) clear ;
    deltr
    ;;
4) clear ;
    renewtr
    ;;
5) clear ;
    renew-ip-trojan
    ;;
6) clear ;
    renew-quota-trojan
    ;;
7) clear ;
    cektr
    ;;
8) clear ;
    rtrojan
    ;;
*)
    menu
    ;;
esac