#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
NS=$( cat /etc/xray/dns )
PUB=$( cat /etc/slowdns/server.pub )
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^#! " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		clear
        echo -e "\033[0;33m◈━━━━━━━━◈◈━━━━━━━━◈\033[0m"
        echo -e " PERBARUI AKUN          \E[0m"
        echo -e "\033[0;33m◈━━━━━━━━◈◈━━━━━━━━◈\033[0m"
        echo -e "\033[0;33m◈━━━━━━━━◈◈━━━━━━━━◈\033[0m"
		echo ""
		echo "Tidak Ada Akun"
		echo ""
		echo -e "\033[0;33m◈━━━━━━━━◈◈━━━━━━━━◈\033[0m"
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        menu
	fi

	clear
	echo -e "\033[0;33m◈━━━━━━━━◈◈━━━━━━━━◈\033[0m"
    echo -e " PERBARUI AKUN       \E[0m"
    echo -e "\033[0;33m◈━━━━━━━━◈◈━━━━━━━━◈\033[0m"
  	grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo -e "\033[0;33m◈━━━━━━━━◈◈━━━━━━━━◈\033[0m"
	read -rp "MASUKAN NAMA : " user
    if [ -z $user ]; then
    menu
    else
    rm -f /etc/kyt/limit/trojan/ip/${user}
    rm -f /etc/trojan/$user
    read -p "Expired (days): " masaaktif
    read -p "Limit User (GB): " Quota
    read -p "Limit User (IP): " iplim
    exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    mkdir -p /etc/kyt/limit/trojan/ip
echo ${iplim} >> /etc/kyt/limit/trojan/ip/${user}
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $masaaktif))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "/#! $user/c\#! $user $exp4" /etc/xray/config.json
    sed -i "/#! $user/c\#! $user $exp4" /root/akun/trojan/.trojan.conf
    systemctl restart xray > /dev/null 2>&1
    clear
    echo -e "\033[0;33m◈━━━━━◈◈━━━━━◈\033[0m"
    echo "AKUN BERHASIL DIPERBARUI"
    echo -e "\033[0;33m◈━━━━━◈◈━━━━━◈\033[0m"
    echo -e "\033[0;33m◈━━━━━━━━◈◈━━━━━━━━◈\033[0m"
    echo ""
    echo "Domain  : $(cat /etc/xray/domain)"
    echo "Pengguna  : $user"
    echo "Tambahan Hari  : $masaaktif Hari"
    echo "Tanggal Exp  : $exp4"
    echo "Batas Kuota  : $Quota"
    echo "Batas IP  : $iplim"
    echo ""
    echo -e "\033[0;33m◈━━━━━━━━◈◈━━━━━━━━◈\033[0m"
    echo ""
    read -n 1 -s -r -p "ENTER UNTUK KEMBALI KE MENU"
    menu
    fi